# Generated by Django 5.0.7 on 2024-07-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
                ('description_category', models.TextField(max_length=1000)),
                ('slug_category', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug_forum', models.SlugField()),
                ('autor_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='LikeForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomber_likes', models.IntegerField()),
                ('autor_like_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('forum_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_message', models.TextField(max_length=500)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('autor_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('forum_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forum')),
            ],
        ),
        migrations.CreateModel(
            name='LikeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomber_likes', models.IntegerField()),
                ('autor_like_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('message_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('forum_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.forum')),
            ],
        ),
    ]
