# Generated by Django 5.0.7 on 2024-07-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
